# Generated by Django 4.0.4 on 2022-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUsernameNftMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(db_index=True, default=-1, unique=True)),
                ('twitter_username', models.CharField(max_length=100)),
                ('is_following', models.BooleanField(default=False)),
            ],
        ),
    ]
